# -*- coding: utf-8 -*-
"""apriori_on_genes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1te7daZDsryV1tnRM0Akq0FZBacxw_Wpc
"""

import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules
i

df = pd.read_csv("/content/drive/MyDrive/train_test_data/train_encoded.csv")

df = df.drop(columns=["Genetic Disorder", "Disorder Subclass"], errors="ignore")

binary_df = df.applymap(lambda x: 1 if x == 1 else 0)

