# -*- coding: utf-8 -*-
"""DS&A_Lab05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bnUYY0tKHd-NbzwQT4pTa3rwiLcqVunH
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt # from matplotlib import pyplot as plt
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm

data = pd.read_csv('salary_data.csv')

data.info()

data.shape

data.describe()

data["Salary"].isnull().sum()

len(data)

data.shape[1]

data.head()

X = data["YearsExperience"]
y = data["Salary"]

X.head()

y.head(1)

plt.scatter(X,y)
plt.title("Salary - Experience in Years")
plt.xlabel("Experience in Years")
plt.ylabel("Salary")
plt.show()

model = LinearRegression()
X = X.values.reshape(-1,1)
model.fit(X,y)

model.intercept_

model.coef_

model.predict(np.array([[5], [10], [20]]))

x1 = sm.add_constant(X)
results = sm.OLS(y,x1).fit()
results.summary()

