# -*- coding: utf-8 -*-
"""KMeans.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-7dlH7m7LIONiXJ1v3OtJOU3IlcW_PDE
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

sns.set()
import warnings
warnings.filterwarnings('ignore')

data = pd.read_csv("Countries.csv")

data.head()

plt.scatter(data['Longitude'], data['Latitude'])
plt.xlabel("Longitude")
plt.ylabel("Latitude")

X = data.iloc[:, 1:3]

X

scaler = StandardScaler()
X_scaled = pd.DataFrame(scaler.fit_transform(X), columns=X.columns)

X_scaled

plt.scatter(X_scaled["Longitude"], X_scaled["Latitude"])

km = KMeans(n_clusters=3)

km

km.fit(X)

km

identified_clusters = km.fit_predict(X)

identified_clusters

data["Cluster"] = identified_clusters

data

plt.scatter(data["Longitude"], data["Latitude"], data["Cluster"], cmap="rainbow")
plt.xlabel("Longitude")
plt.ylabel("Latitude")
plt.show()

wcss = []
k_values = range(1,11)
for k in k_values:
  model = KMeans(n_clusters=k)
  model.fit(X)
  wcss.append(model.inertia_)

wcss

plt.plot(k_values, wcss)

model = KMeans(n_clusters=3)
pred = model.fit_predict(X)

pred

data["Clusters_After_Elbow"] = pred

data

data.Clusters_After_Elbow.unique()

c1 = data[data.Clusters_After_Elbow == 0]
c2 = data[data.Clusters_After_Elbow == 1]
c3 = data[data.Clusters_After_Elbow == 2]

c1

c2

c3

plt.scatter(c1.Longitude, c1.Latitude, color="green")
plt.scatter(c2.Longitude, c2.Latitude, color="red")
plt.scatter(c3.Longitude, c3.Latitude, color="blue")
plt.scatter(model.cluster_centers_[: , 0], model.cluster_centers_[: , 1], color="black")
plt.xlabel("Longitude")
plt.ylabel("Latitude")
plt.show()

model.cluster_centers_

