# -*- coding: utf-8 -*-
"""RandomForest_in_Comparison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l0cG0fca8GYZCyjhsw-WCRMHsldEnt05
"""

import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

data = load_breast_cancer()
X, y = data.data, data.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

tree_list = []
for i in range(250):
  tree = DecisionTreeClassifier(max_features='sqrt')
  subet_indicies = np.random.choice(np.arange(len(X_train)), size=len(X_train) // 2)
  X_train_subset = X_train[subet_indicies]
  y_train_subset = y_train[subet_indicies]
  tree.fit(X_train_subset, y_train_subset)
  tree_list.append(tree)

preds = []
for i, tree in enumerate(tree_list):
  individual_preds = tree.predict(X_test)
  individual_accuracy = accuracy_score(y_test, individual_preds)
  print(f"Tree {i+1} accuracy : {individual_accuracy}")
  preds.append(individual_preds)


preds = np.array(preds)
mean_preds = np.mean(preds, axis=0)
ensemble_predictions = np.round(mean_preds)

ensemble_accuracy = accuracy_score(y_test, ensemble_predictions)
print(f"\nEnsemble accuracy : {ensemble_accuracy}")

rForest = RandomForestClassifier(n_estimators=100)
rForest.fit(X_train, y_train)
rForest_preds = rForest.predict(X_test)

print(f"Random Forest accuracy : {accuracy_score(y_test, rForest_preds)}")

